name: Build APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Permite iniciar a compilação manualmente clicando em um botão

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Dependências (Flet e Flet Audio)
        run: pip install -r requirements.txt

      - name: Compilar APK do Aplicativo
        # O Flet vai ler automaticamente o requirements.txt para incluir o flet_audio no APK
        # A flag --yes serve para aceitar automaticamente qualquer download (ex: Flutter SDK) que o Flet precise fazer na nuvem.
        run: flet build apk --yes

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: financas-mobile-apk
          path: build/apk/app-release.apk
